<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>error 404</title>
    <link rel="stylesheet" href="css/master.css">
    <link rel="stylesheet" href="css/error404.css">
  </head>
  <body>
    <section class="notFound">
          <div class="img">
            <img src="https://assets.codepen.io/5647096/backToTheHomepage.png" alt="Back to the Homepage"/>
            <img src="https://assets.codepen.io/5647096/Delorean.png" alt="El Delorean, El Doc y Marti McFly"/>
          </div>
          <div class="text NeonEffect">
            <h1>404</h1>
            <h2>PAGE NOT FOUND</h2>
            <h3>BACK TO HOME?</h3>
            <a href="/" class="yes">YES</a>
            <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">NO</a>
        </div>
    </section>
  </body>
</html>