         <main>
            <h2 class="NeonEffect" style="color: white; text-align: center;">Mon Parcours d'étude</h2>
            <div class="timeline">
                <div class="container left">
                  <div class="date">2020</div>
                  <i class="icon fa fa-home"></i>
                  <div class="content Neon">
                    <h2>1re année de Licence d'Histoire - Limoges</h2>
                    <p>
                      Licence que j'ai débuté au mois de Septembre 2020 mais que je n'ai pas terminé avec comme motivation de me réorienter en développement Informatique
                    </p>
                  </div>
                </div>
                <div class="container right">
                  <div class="date">2021</div>
                  <i class="icon fa fa-gift"></i>
                  <div class="content Neon">
                    <h2>DU REAGIR - Limoges</h2>
                    <p>
                      Le dispositif du DU REAGIR est proposé par l'académie universitaire de Limoges pour permettre aux étudiant désireux de se réorienter de travailler à la construction d'un nouveau projet professionnel 
                    </p>
                  </div>
                </div>
                <div class="container left">
                  <div class="date">2022</div>
                  <i class="icon fa fa-user"></i>
                  <div class="content Neon">
                    <h2>1re Année de BTS SIO SLAM - Toulouse</h2>
                    <p>
                      J'ai réalisé une année de BTS SIO spécialité SLAM au Lycée Ozenne à Toulouse.
                      Je n'ai cependant pas fait la 2nd année car je désirais me spécialiser en developpement Web en accédant à une formation professionnel dédié au développement web. 
                    </p>
                  </div>
                </div>
                <div class="container right">
                  <div class="date">2022</div>
                  <i class="icon fa fa-running"></i>
                  <div class="content Neon">
                    <h2>Formation Bac +2 développement web et web mobile - Toulouse</h2>
                    <p>
                     Formation de 3 mois réalisé avec Webforce3 Toulouse. 
                    </p>
                  </div>
                </div>
                <div class="container left">
                  <div class="date">2023</div>
                  <i class="icon fa fa-running"></i>
                  <div class="content Neon">
                    <h2>Formation Concepteur Designer User Interface (CDUI) - Toulouse</h2>
                    <p>
                     Formation de 9 mois que j'ai débuté au mois de Septembre 2023 avec BGE Sud-Ouest afin  de me former aux métiers de Web Designer et d'Intégrateur Web
                    </p>
                  </div>
                </div>
              </div>
          </main>