         <main>
            <h2 class="NeonEffect" style="color: white; text-align: center;">Mon Parcours d'étude</h2>
            <div class="timeline">
                <div class="container left">
                  <div class="date">2018</div>
                  <i class="icon fa fa-gift"></i>
                  <div class="content Neon">
                    <h2>1re STMG - Gaillac</h2>
                    <p>
                      1re STMG réalisé au lycée Victor-Hugo.
                    </p>
                  </div>
                </div>
                <div class="container right">
                  <div class="date">2019</div>
                  <i class="icon fa fa-gift"></i>
                  <div class="content Neon">
                    <h2>Terminale STMG - Gaillac</h2>
                    <p>
                      Terminale STMG spécialité Gestion Finance des Entreprises (GFE) réalisé au lycée Victor-Hugo. 
                    </p>
                  </div>
                </div>
                <div class="container left">
                  <div class="date">2020</div>
                  <i class="icon fa fa-home"></i>
                  <div class="content Neon">
                    <h2>1re année de Licence d'Histoire - Limoges</h2>
                    <p>
                      Après n'avoir pas eu la possibilité d'entrer en DUT MMI (Métier du Multimédia et d'Internet), 
                      j'ai été contraint d'accepter mon vœux de secours sur Parcoursup en Licence d'Histoire.
                    </p>
                  </div>
                </div>
                <div class="container right">
                  <div class="date">2021</div>
                  <i class="icon fa fa-gift"></i>
                  <div class="content Neon">
                    <h2>DU REAGIR - Limoges</h2>
                    <p>
                      Mon projet ayant toujours été de devenir Développeur, je décide donc au début de l'année 2021 d'entrer au DU REAGIR : 
                      Un dispositif proposé par l'université de Limoges pour préparer une réorientation,
                      je finis ce dispositif en étant sélectionné pour entrer en BTS SIO au Lycée Ozenne à Toulouse. 
                    </p>
                  </div>
                </div>
                <div class="container left">
                  <div class="date">2022</div>
                  <i class="icon fa fa-user"></i>
                  <div class="content Neon">
                    <h2>1re Année de BTS SIO SLAM - Toulouse</h2>
                    <p>
                      J'ai réalisé une année de BTS SIO spécialité SLAM au Lycée Ozenne à Toulouse.
                      Je n'ai cependant pas fait la 2nd car je souhaitais me spécialiser en dev Web et donc trouver une formation plus adapté. 
                    </p>
                  </div>
                </div>
                <div class="container right">
                  <div class="date">2022</div>
                  <i class="icon fa fa-running"></i>
                  <div class="content Neon">
                    <h2>Formation Bac +2 développement web et web mobile - Toulouse</h2>
                    <p>
                      Après ma formation en BTS que j'avais trouvé trop général, je souhaitais une formation plus approfondie en développement web.
                      C'est pour cela que j'ai choisi la formation RNCP Développement Web et Web mobile (Niveau 5) chez Webforce3. 
                    </p>
                  </div>
                </div>
              </div>
          </main>