      <main>
          <h2 class="NeonEffect" style="color: white; text-align: center;">Languages maitrisés</h2>
          <div class="slider">
            <div class="slide-container swiper">
              <div class="slide-content">
                <div class="card-wrapper swiper-wrapper">
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image Neon">
                        <img src="./src/images/langages/HTML.svg" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">HTML 5</h2>
                      <p class="description">HTML (HyperText Markup Language) est un langage de balisage utilisé pour la création et la structuration de pages web. 
                        Il permet de décrire le contenu d'une page web en utilisant des balises et des attributs qui indiquent comment le contenu doit être affiché dans le navigateur. 
            
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image Neon">
                        <img src="./src/images/langages/css.svg" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">CSS 3</h2>
                      <p class="description">CSS (Cascading Style Sheets) est un langage de style utilisé pour définir la présentation visuelle des pages web écrites en HTML ou XML. 
                        Il permet de définir des styles pour différents éléments de la page tels que les couleurs, les polices de caractères, les marges, les bordures, les arrière-plans.</p>
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
                      <div class="card-image Neon">
                        <img src="./src/images/langages/Javascript.svg" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">Javascript</h2>
                      <p class="description">JavaScript est un langage de programmation de script utilisé pour rendre les pages web interactives et dynamiques. Il permet aux développeurs de créer des fonctionnalités avancées telles que des animations, 
                        des menus déroulants, des formulaires interactifs et bien plus encore..</p>
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image Neon">
                        <img src="./src/images/langages/Php-logo.png" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">PHP</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image Neon">
                        <img src="./src/images/langages/SQL-logo.jpg" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">SQL</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image Neon">
                        <img src="./src/images/langages/Angular.png" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">Angular</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
          
                      
                    </div>
                  </div>
                </div>
              </div>
          
              <div class="swiper-button-next swiper-navBtn"></div>
              <div class="swiper-button-prev swiper-navBtn"></div>
              <div class="swiper-pagination"></div>
            </div>
          </div>
      </main>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <script src="./src/js/script.js"></script>
