        <main>
          <h2 class="NeonEffect" style="text-align: center; color: white;">Mes Projets et Exercices</h2>
          <br>
          <h3 class="NeonEffect" style="text-align: center; color: white;">1re Année de BTS SIO</h3>
          <div class="ag-format-container">
            <div class="ag-courses_box">
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    Café des mondes : <h6>Conception d'un site HTML-CSS statique. </h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      04.11.2021 - 12.12.2021
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
        
                  <div class="ag-courses-item_title">
                    Projet GLPI : <h6>Simulation d'une gestion de tickets.</h6>
                  </div>
        
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      04.01.2022 - 10.02.2022
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
        
                  <div class="ag-courses-item_title">
                    Projet GSB : <h6>Conception d'un site dynamique</h6>
                  </div>
        
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      12.02.2022 - 01.06.2022
                    </span>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <h3 class="NeonEffect" style="text-align: center; color: white;">Formation Bac+2 Webforce3</h3>
          <div class="ag-format-container">
            <div class="ag-courses_box">
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    ACME : <h6>Conception d'un site static avec la fonction flex</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Start:
                    <span class="ag-courses-item_date">
                      17.10.2022 - 20.10.2022
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    POO "Pokémon" : <h6>Conception d'un progamme en POO en Javascript</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      21.12.2022 - 23.12.2022
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    Todolist : <h6>Conception d'une todolist dynamique en PHP</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      02.01.2023 - 09.01.2023
                    </span>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <h3 class="NeonEffect" style="text-align: center; color: white;">Personnel...</h3>
          <div class="ag-format-container">
            <div class="ag-courses_box">
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    Portoflio : <h6>Développement d'un portfolio de compétences résumant l'ensemble de mon parcours.</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                     Durée :
                    <span class="ag-courses-item_date">
                       16.02.2023 - 04.04.2023
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    Projet Symfony : <h6>Développement de la page Principal d'un projet coopératif : Androcode</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      A venir...
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
        
                  <div class="ag-courses-item_title">
                    Application JAVA :  <h6>Récreation du menu de la Nintendo Switch en HTML/CSS/JAVA</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      A venir...
                    </span>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </main>
