        <main>
          <h2 class="NeonEffect" style="text-align: center; color: white;">Mes Projets et Exercices</h2>
          <br>
          <h3 class="NeonEffect" style="text-align: center; color: white;">1re Année de BTS SIO</h3>
          <div class="ag-format-container">
            <div class="ag-courses_box">
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    Café des mondes : <h6>Conception d'un site HTML-CSS statique. </h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      04.11.2021 - 12.12.2021
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
        
                  <div class="ag-courses-item_title">
                    Projet GLPI : <h6>Simulation d'une gestion de tickets.</h6>
                  </div>
        
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      04.01.2022 - 10.02.2022
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
        
                  <div class="ag-courses-item_title">
                    Projet GSB : <h6>Conception d'un site dynamique</h6>
                  </div>
        
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      12.02.2022 - 01.06.2022
                    </span>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <h3 class="NeonEffect" style="text-align: center; color: white;">Personnel...</h3>
          <div class="ag-format-container">
            <div class="ag-courses_box">
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    Portoflio : <h6>Développement d'un portfolio de compétences résumant l'ensemble de mon parcours.</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                     Durée :
                    <span class="ag-courses-item_date">
                       16.02.2023 - 04.04.2023
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
                  <div class="ag-courses-item_title">
                    Projet Androcode : <h6>Projet personnel en coopération avec un proche réunissant différentes applications web</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      En cours
                    </span>
                  </div>
                </a>
              </div>
              <div class="ag-courses_item Neon">
                <a href="#" class="ag-courses-item_link">
                  <div class="ag-courses-item_bg"></div>
        
                  <div class="ag-courses-item_title">
                   AndroStage :  <h6>Création d'une application mobile de suivi de stage</h6>
                  </div>
                  <div class="ag-courses-item_date-box">
                    Durée:
                    <span class="ag-courses-item_date">
                      A venir...
                    </span>
                  </div>
                </a>
              </div>
              <!-- <h3 class="NeonEffect" style="text-align: center; color: white;">Formation Concepteur Designer User Interface (CDUI)</h3>
              <div class="ag-format-container">
                <div class="ag-courses_box">
                  <div class="ag-courses_item Neon">
                    <a href="#" class="ag-courses-item_link">
                      <div class="ag-courses-item_bg"></div>
                      <div class="ag-courses-item_title">
                        La Cave d'antoine : <h6>Refonte d'un site internet qui va de la prise en compte du besoin client à la conception web</h6>
                      </div>
                      <div class="ag-courses-item_date-box">
                        Durée:
                        <span class="ag-courses-item_date">
                          Octobre 2023 - Juillet 2024
                        </span>
                      </div>
                  </a>
              </div> -->
            </div>
          </div>
        </main>
